# Load Kinecal Data ELEC872 Project
### Leonard Moen | November 16th 2022

In [3]:
import pandas as pd
import numpy as np
import os
import importlib

import LoadKinecalFunctions
from LoadKinecalFunctions import *

importlib.reload(LoadKinecalFunctions)

<module 'LoadKinecalFunctions' from 'c:\\Users\\Cam Bish\\codeRepos\\KINECAL Balance Assessment\\KINECAL-Balance-Assessment\\LoadKinecalFunctions.py'>

In [230]:

excercise_list = ['Quiet-Standing-Eyes-Closed', 'Quiet-Standing-Eyes-Open', 'Semi-Tandem-Balance', 'Tandem-Balance']

QS_Closed_df = readKinecalFiles(excercise_list[0]) 
QS_Open_df = readKinecalFiles(excercise_list[1]) 
Semi_Tandem_df = readKinecalFiles(excercise_list[2]) 
Tandem_df = readKinecalFiles(excercise_list[3]) 
#dataset_df.to_csv('test.csv')

### Seperate X and Y Dataframes

In [240]:
y_df = QS_Closed_df.iloc[:,0:8]
y_df = y_df.drop(columns='movement')

QS_Closed_x_df =QS_Closed_df.iloc[: ,9:-1]
QS_Open_x_df =QS_Open_df.iloc[: ,9:-1]
Semi_Tandem_x_df =Semi_Tandem_df.iloc[: ,9:-1]
Tandem_x_df =Tandem_df.iloc[: ,9:-1]

### Replace Missing Data With Mean of That Class

In [241]:
QS_Closed_x_df = replaceMissingValues(QS_Closed_x_df,QS_Closed_y_df)
QS_Open_x_df = replaceMissingValues(QS_Open_x_df,QS_Open_y_df)
Semi_Tandem_x_df = replaceMissingValues(Semi_Tandem_x_df,Semi_Tandem_y_df)
Tandem_x_df = replaceMissingValues(Tandem_x_df,Tandem_y_df)


[ 2 14 15]
[ 2 17 29 34 71]
[ 2 14 17 31 33 60 66]
[13 14 17 29 31 33 36 37 55 60 66 74 77]
